spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chatengine}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:chatuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:chatpass}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name=Chat Engine
info.app.version=1.0.0